---
title: "BMP time series regression"
author: "Sarah Daly"
date: "'April 21, 2020"
output: word_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Purpose:  Examine the time series data of the individual BMP tests (n=3) via plotting and smoothing to known data curves; calculate coefficients of fit and kinetic constants.  Biotonw only.  


https://ourcodingclub.github.io/2017/04/26/time.html 
#Set Working Directory
```{r}
setwd("C:/Users/dalys/OneDrive/Desktop/PHD paper notes/BMP/github/Methane Yield")
```

#Load packages
```{r}
library(ggplot2)
library(forecast)
library(dplyr)
library(colortools)
library(plyr) #plyr should be loaded before dplyr
library(dplyr)
library(gridExtra)

```



#Visuliaze BMP data (g VS added)
```{r}
###########LOOP Plot###########################################################
data<-read.csv("20200228_BMPProject_TotalBMP_v02_sd.csv",header=TRUE,na.strings="NA",stringsAsFactors=FALSE)
head(data)
dim(data)

data$Batch<-data$Batch #Needs to start with a 1 for a loop
dim(data)
#Plot valeus for each batch tests
batch<-sort(unique(data$Batch))
names <- sort(unique(data$Name))
graph <- list() #initialize graph list

#batch=c(2,3,4,5)
i=1
#for(i in batch){
while (i<=length(batch)){
#Average data by name
  
Batch <- subset(data, data$Batch==i, 
select=c(Day,CH4_Yield_VS_added,Location,Name,Date,pH))
Batch
Batch$CH4_Yield_VS_added=as.numeric(Batch$CH4_Yield_VS_added)
  
#Average data
cdata <- ddply(Batch, c("Name", "Day"), summarise,
               mean = mean(CH4_Yield_VS_added,na.rm=TRUE),
               sd   = sd(CH4_Yield_VS_added,na.rm=TRUE)
)
#Get plot title 
#title=paste(Batch [1,3] , Batch[1,5],sep=" ")
title=paste("Test" , i,sep=" ")

p1<-ggplot(cdata, aes(group=Name, colour=Name, x= Day, y= mean)) + 
geom_line() + 
geom_point() + 
geom_errorbar(aes(ymin = mean-sd, ymax= mean + sd), 
         width=.2, position=position_dodge(0.05))+
#stat_summary(geom = "line", fun.y = mean) +
#stat_summary(geom = "errorbar", fun.data = sd, position = position_dodge(0.4), width=0.08)+
theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), #Remove background
panel.background = element_blank(), axis.line = element_line(colour = "black"))+
theme(text = element_text(size=12,colour="black",face="bold"), 
     axis.text.x = element_text(angle=0,hjust = 1, colour = 'black'),
     axis.text.y = element_text(angle = 0, hjust = 1, colour = 'black'),
     plot.title= element_text(hjust = 0.9),legend.title = element_blank())+
  ggtitle(title)+
  theme(plot.title = element_text(hjust = 0.5))+
  theme(axis.ticks.length=unit(-0.25, "cm"), axis.text.x = element_text(margin=unit(c(0.5,0.5,0.5,0.5), "cm")), axis.text.y = element_text(margin=unit(c(0.5,0.5,0.5,0.5), "cm")) )+
    scale_x_continuous(expand=c(0,0),name="Day", limits=c(0, 60)) +
  scale_y_continuous(expand=c(0,0),name=expression(bold(paste("BMP (mL CH"[4]," g VS "^"-1",")"))), limits=c(0, 250))+
  #Make a small legend       
  guides(shape = guide_legend(override.aes = list(size = 1)), #Decrease size of shape elements
               color = guide_legend(override.aes = list(size = 1))) +#Decrease size of color elements
        theme(legend.text  = element_text(size = 10),
              legend.key.size = unit(0.2, "lines"),
              legend.title = element_blank())

graph[[i]]= p1  # add each plot into plot list
   print(i)
   print(p1)

#dev.off()
while (!is.null(dev.list()))  dev.off()
i=i+1
   }
dev.new()
do.call(grid.arrange,graph)

tiff("BMP yields.tif", res=600, compression = "lzw", height=9, width=13, units="in")
do.call(grid.arrange,graph)
dev.off()

pdf("BMP yields.pdf", height=7, width=13)
do.call(grid.arrange,graph)
dev.off()
```

